# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the necessary Python packages
RUN pip install --no-cache-dir apscheduler psycopg2-binary pika redis

RUN chmod +x consumer.py

ENTRYPOINT ["python", "-u", "./consumer.py"]